apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yv1x
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-yv1x@sha256:2e909a660babd8fa9f60365973d91132c9bc2dd057eb54bcf69518bcc6a8f2d4
        name: my-nodejs
        resources: {}
status: {}
